server.port=8761

spring.application.name=discovery-service

# Eureka server configs
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=prometheus,metrics,info,health,shutdown,beans

# Health endpoint details
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true

# Enable shutdown
management.endpoint.shutdown.enabled=true

# Info endpoint env
management.info.env.enabled=true
