
security.jwt.secret=MySuperStrongJWTSecretKeyForEcommerceApp123456
security.jwt.expiration-ms=86400000

logging.level.org.springframework.web=TRACE
spring.application.name=order-service
server.port=8088

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

# Enable caching in the service
spring.cache.type=redis

# Eureka client configs
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Prefer IP over hostname
eureka.instance.prefer-ip-address=true

spring.cloud.loadbalancer.retry.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=nithin123
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/orderdb
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# Kafka bootstrap
spring.kafka.bootstrap-servers=localhost:9092

# Consumer basics
spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Error handling wrapper
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate to JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Default event type to deserialize into (shared event in common module)
spring.kafka.consumer.properties.spring.json.value.default.type=com.ecom.common.events.PaymentEvent

# Allow deserialization of events in your common package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ecom.common.events

logging.level.root=INFO
logging.level.com.ecom.orderservice=INFO

management.endpoints.web.exposure.include=prometheus,metrics,info,health,shutdown,beans

# Health endpoint details
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true

# Enable shutdown
management.endpoint.shutdown.enabled=true

# Info endpoint env
management.info.env.enabled=true


